### ISSUE TITLE
FILTRO: qualche problema sulle stringhe con apice.

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#32]
Se nel campo metto la stringa " Dr.Clauder's", il filtro non tira fuori alcuna offerta..
Nella console vedo diversi errori, molto probabilmente dovuti al apice presente nella stringa.

![image](https://cloud.githubusercontent.com/assets/16100767/11870703/5af85966-a4ca-11e5-8518-b105ace92bb3.png)
![errore](https://cloud.githubusercontent.com/assets/16100767/11870717/8069a57e-a4ca-11e5-8669-2ffc37ceef99.png)

versione 0.4beta

**Comment by andreafortuna** [comment]
Done!
