### ISSUE TITLE
Termini e Condizioni

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#38]
Abilitare la mascherina per visualizzare il testo.
Abilitare il backend per poter editare il testo.

versione 0.4beta

**Comment by andreafortuna** [comment]
Aggiunto nell'app.

Testo configurabile da qui:
http://www.pohiri.com/guardaqua/API/BE/OPTIONS/edit.php?KEY=AppTerms_IT

**Comment by cdesilv** [comment]
Pur agendo sul backend ed inserendo un po' di testo....ed aggiornando la app...il testo non viene recepito
