### ISSUE TITLE
Strano errore nel codice.

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#39]
Guardando nella console, vedo questo errore....e' qualcosa che deve essere sistemato o rimosso?
![image](https://cloud.githubusercontent.com/assets/16100767/11871879/956b765c-a4d2-11e5-87b9-f3d102ae39b9.png)

versione 0.4beta

**Comment by andreafortuna** [comment]
Normale: l'app e' fruita tramite HTTP, e gmaps segnala che HTTPS sarebbe meglio :-)
