### ISSUE TITLE
Box commento

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#45]
Attenzione se uno agisce sull'angolo dx in basso del box commento succede questo:
![image](https://cloud.githubusercontent.com/assets/16100767/11901064/cda82326-a5a9-11e5-8132-4266f8757e4b.png)

**Comment by andreafortuna** [comment]
Avviene solo su desktop: su mobile il ridimensionamento e' disabilitato di default.
