### ISSUE TITLE
Miglioria layout maschere.

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#57]
Ho preso spunto da alcune maschere di data entry e da safari.
Secondo me le gui potrebbero essere piu' eleganti se adottassimo alcuni accorgimenti riportati nell'immagine allegata (discutiamone).
![image](https://cloud.githubusercontent.com/assets/16100767/12229377/543c7dba-b847-11e5-8b12-e8c649e21944.png)

**Comment by andreafortuna** [comment]
Pronto, lo rilascio con la versione 0.6B
