### ISSUE TITLE
INSERIMENTO OFFERTA: UUU doppia entry nel DB

### ISSUE THREAD

**Issue by cdesilv** [GuardaQua/guardaqua.github.io#70]
/!\ una volta concluso l'inserimento e dato un'occhiata al DB, a fronte dell'inserimento vedo due record.
![image](https://cloud.githubusercontent.com/assets/16100767/13603410/59b0ccec-e53d-11e5-8ec7-f0cf59ef63f9.png)

**Comment by andreafortuna** [comment]
Applicato workaround quick-n-dirty
